import React, { useEffect, useRef, useState } from 'react';
import { io } from 'socket.io-client';
import { Send, Paperclip, Smile, Plus, Search, X, MessageCircle, Check, CheckCheck, ArrowLeft } from 'lucide-react';
import api, { searchAPI, chatAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';

const SOCKET_URL = (import.meta.env.VITE_API_URL || 'http://localhost:5000/api').replace(/\/api\/?$/, '');
const EMOJIS = ['😀','😂','😍','🥰','😎','👍','❤️','🔥','🎉','👏','🙏','😊','😢','😮','🤝','✨'];

export default function ChatPage() {
  const { user } = useAuth();
  const [chats,setChats]=useState([]),[selectedChat,setSelectedChat]=useState(null),[messages,setMessages]=useState([]);
  const [newMessage,setNewMessage]=useState(''),[loading,setLoading]=useState(true),[newChatOpen,setNewChatOpen]=useState(false);
  const [userQuery,setUserQuery]=useState(''),[userResults,setUserResults]=useState([]),[phoneQuery,setPhoneQuery]=useState(''),[inviteNumber,setInviteNumber]=useState('');
  const [phoneSearching,setPhoneSearching]=useState(false),[sending,setSending]=useState(false),[emojiOpen,setEmojiOpen]=useState(false);
  const [galleryFile,setGalleryFile]=useState(null);
  const sendingRef=useRef(false), socketRef=useRef(null), selectedChatRef=useRef(null), endRef=useRef(null), galleryRef=useRef(null);
  useEffect(()=>{selectedChatRef.current=selectedChat},[selectedChat]);
  useEffect(()=>{
    socketRef.current=io(SOCKET_URL,{auth:{token:localStorage.getItem('token')}});
    socketRef.current.on('new_message',data=>{if(selectedChatRef.current?.id===data.chatId){setMessages(prev=>prev.some(m=>m.id===data.id)?prev:[...prev,data]); if(data.senderId!==user?.id) api.post(`/chats/${data.chatId}/read`).catch(()=>{});}});
    socketRef.current.on('message_read',({chatId,messageIds})=>{if(selectedChatRef.current?.id!==chatId)return;const ids=new Set(messageIds||[]);setMessages(prev=>prev.map(m=>ids.has(m.id)?{...m,isRead:true}:m));});
    fetchChats(); return()=>socketRef.current?.disconnect();
  },[]);
  useEffect(()=>{if(!selectedChat)return; socketRef.current?.emit('join_chat',selectedChat.id); fetchMessages(selectedChat.id);},[selectedChat]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[messages]);
  const fetchChats=async()=>{try{const r=await api.get('/chats');setChats(r.data.data||[])}catch(e){console.error(e)}finally{setLoading(false)}};
  const fetchMessages=async id=>{try{const r=await api.get(`/chats/${id}/messages`);setMessages(r.data.data||[]);await api.post(`/chats/${id}/read`)}catch(e){console.error(e)}};
  const sendMessage=async()=>{const content=newMessage.trim();if(!content&&!galleryFile||!selectedChat||sendingRef.current)return;sendingRef.current=true;setSending(true);try{let mediaUrl=null;if(galleryFile){const form=new FormData();form.append('file',galleryFile);const up=await api.post('/posts/upload',form,{headers:{'Content-Type':'multipart/form-data'}});mediaUrl=up.data.data.url;}const r=await chatAPI.sendMessage(selectedChat.id,content,mediaUrl);const sent=r.data.data;setMessages(prev=>prev.some(m=>m.id===sent.id)?prev:[...prev,sent]);setNewMessage('');setGalleryFile(null);setEmojiOpen(false);fetchChats()}catch(e){console.error(e);alert(e.response?.data?.message||'Failed to send message')}finally{sendingRef.current=false;setSending(false)}};
  const other=chat=>chat?.participants?.find(p=>p.id!==user?.id)||chat?.participants?.[0];
  const startChatWith=async u=>{try{const r=await chatAPI.createChat(u.id);setNewChatOpen(false);setUserResults([]);setUserQuery('');await fetchChats();setSelectedChat(r.data.data)}catch(e){alert(e.response?.data?.message||'Could not start chat')}};
  const runUserSearch=async q=>{setUserQuery(q);if(!q.trim()){setUserResults([]);return}try{const r=await searchAPI.search(q.trim(),'users');setUserResults((r.data.data?.users||[]).filter(u=>u.id!==user?.id))}catch(e){console.error(e)}};
  const searchByPhone=async()=>{const q=phoneQuery.trim();if(!q)return;setPhoneSearching(true);try{const r=await searchAPI.search(q,'users');const us=(r.data.data?.users||[]).filter(u=>u.id!==user?.id);if(us[0]){await startChatWith(us[0]);setPhoneQuery('')}else{setInviteNumber(q);alert('No RA Social account found. You can invite them.')}}finally{setPhoneSearching(false)}};
  const inviteMessage=`Join me on RA Social! ${window.location.origin}`;
  const inviteViaWhatsApp=()=>{const digits=inviteNumber.replace(/\D/g,'');window.open(`https://wa.me/${digits}?text=${encodeURIComponent(inviteMessage)}`,'_blank','noopener,noreferrer')};
  const appendEmoji=e=>setNewMessage(v=>v+e);
  const galleryChanged=e=>{const f=e.target.files?.[0];if(f){setGalleryFile(f)}e.target.value=''};

  return <div className="pt-16 h-[100dvh] flex overflow-hidden bg-white">
    <section className={`${selectedChat?'hidden md:flex':'flex'} w-full md:w-[340px] shrink-0 flex-col border-r border-gray-200`}>
      <div className="p-4 border-b flex items-center justify-between"><h2 className="text-xl font-bold">Messages</h2><button onClick={()=>setNewChatOpen(true)} className="p-2 bg-purple-600 text-white rounded-full"><Plus className="w-5 h-5"/></button></div>
      <div className="flex-1 overflow-y-auto">{loading?<div className="text-center py-20 text-gray-400">Loading chats...</div>:chats.map(c=>{const o=other(c);return <button key={c.id} onClick={()=>setSelectedChat(c)} className={`w-full flex items-center gap-3 p-4 text-left hover:bg-gray-50 ${selectedChat?.id===c.id?'bg-purple-50':''}`}><img src={o?.avatarUrl||`https://i.pravatar.cc/150?u=${o?.id}`} className="w-12 h-12 rounded-full object-cover shrink-0"/><div className="min-w-0 flex-1"><h3 className="font-semibold truncate">{o?.fullName||o?.username}</h3><p className="text-sm text-gray-500 truncate">{c.messages?.[0]?.content||'Start chatting'}</p></div></button>})}</div>
    </section>
    <section className={`${selectedChat?'flex':'hidden md:flex'} flex-1 min-w-0 flex-col h-full`}>
      {selectedChat?<>
        <header className="h-16 shrink-0 border-b flex items-center gap-3 px-3 md:px-4 bg-white"><button onClick={()=>setSelectedChat(null)} className="md:hidden p-2 rounded-full hover:bg-gray-100 shrink-0"><ArrowLeft className="w-5 h-5"/></button><img src={other(selectedChat)?.avatarUrl||'https://i.pravatar.cc/150'} className="w-9 h-9 rounded-full object-cover shrink-0"/><div className="min-w-0 flex-1"><h3 className="font-semibold truncate">{other(selectedChat)?.fullName||other(selectedChat)?.username}</h3><p className="text-xs text-green-600">Private chat</p></div></header>
        <div className="flex-1 overflow-y-auto p-3 md:p-4 space-y-2 bg-gray-50">{messages.map((m,i)=><div key={m.id||i} className={`flex ${m.senderId===user?.id?'justify-end':'justify-start'}`}><div className={`max-w-[82%] sm:max-w-[70%] px-3 py-2 rounded-2xl ${m.senderId===user?.id?'bg-purple-600 text-white rounded-br-md':'bg-white text-gray-800 rounded-bl-md shadow-sm'}`}><div className="flex items-end gap-2"><div className="min-w-0">{m.mediaUrl&&<a href={m.mediaUrl} target="_blank" rel="noreferrer" className="block mb-1"><img src={m.mediaUrl} alt="Attachment" className="max-w-[220px] max-h-56 rounded-lg object-contain bg-black/10"/></a>}<p className="whitespace-pre-wrap break-words text-sm">{m.content}</p></div>{m.senderId===user?.id&&(m.isRead?<CheckCheck className="w-4 h-4 text-sky-200 shrink-0"/>:<Check className="w-4 h-4 opacity-70 shrink-0"/>)}</div><p className="text-[10px] mt-1 opacity-70 text-right">{new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</p></div></div>)}<div ref={endRef}/></div>
        {emojiOpen&&<div className="px-3 pt-2 bg-white border-t flex flex-wrap gap-1">{EMOJIS.map(e=><button key={e} onClick={()=>appendEmoji(e)} className="text-2xl p-1 rounded hover:bg-gray-100">{e}</button>)}</div>}
        {galleryFile&&<div className="px-3 pt-2 bg-white text-xs text-gray-500">Attachment selected: {galleryFile.name}</div>}
        <footer className="shrink-0 p-2 md:p-3 border-t bg-white"><div className="flex items-center gap-1.5 max-w-4xl mx-auto"><input value={newMessage} onChange={e=>setNewMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder="Type a message..." style={{fontSize:16}} className="flex-1 min-w-0 px-3 md:px-4 py-2.5 bg-gray-100 rounded-full outline-none"/><button onClick={()=>galleryRef.current?.click()} className="shrink-0 p-2 rounded-full hover:bg-gray-100" title="Gallery"><Paperclip className="w-5 h-5 text-gray-500"/></button><input ref={galleryRef} type="file" accept="image/*,video/*" className="hidden" onChange={galleryChanged}/><button onClick={()=>setEmojiOpen(v=>!v)} className="shrink-0 p-2 rounded-full hover:bg-gray-100" title="Emoji"><Smile className="w-5 h-5 text-gray-500"/></button><button onClick={sendMessage} disabled={sending||(!newMessage.trim()&&!galleryFile)} className="shrink-0 p-3 bg-purple-600 text-white rounded-full disabled:opacity-50" title="Send"><Send className="w-5 h-5"/></button></div></footer>
      </>:<div className="flex-1 items-center justify-center hidden md:flex text-center"><div><MessageCircle className="w-16 h-16 mx-auto text-gray-300 mb-3"/><h3 className="text-xl font-semibold text-gray-700">Select a chat</h3><p className="text-gray-500 mt-1">Choose a conversation</p></div></div>}
    </section>
    {newChatOpen&&<div className="fixed inset-0 z-[100] bg-black/50 flex items-end sm:items-center justify-center"><div className="bg-white w-full sm:max-w-md max-h-[90dvh] overflow-y-auto rounded-t-2xl sm:rounded-2xl"><div className="p-4 border-b flex justify-between"><b>New chat</b><button onClick={()=>setNewChatOpen(false)}><X/></button></div><div className="p-4 space-y-4"><div className="flex gap-2"><input value={phoneQuery} onChange={e=>setPhoneQuery(e.target.value)} placeholder="Mobile number (+91...)" inputMode="tel" className="flex-1 bg-gray-100 rounded-full px-4 py-2 text-sm outline-none"/><button onClick={searchByPhone} disabled={phoneSearching} className="px-4 rounded-full bg-green-500 text-white text-sm">{phoneSearching?'...':'Chat'}</button></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input value={userQuery} onChange={e=>runUserSearch(e.target.value)} placeholder="Search name or username" className="w-full bg-gray-100 rounded-full pl-9 pr-3 py-2 text-sm outline-none"/></div>{userResults.map(u=><button key={u.id} onClick={()=>startChatWith(u)} className="w-full flex items-center gap-3 p-2 text-left rounded-lg hover:bg-gray-50"><img src={u.avatarUrl||`https://i.pravatar.cc/80?u=${u.id}`} className="w-9 h-9 rounded-full"/><span><b className="text-sm">{u.fullName||u.username}</b><small className="block text-gray-500">@{u.username}</small></span></button>)}<div className="border-t pt-4"><input value={inviteNumber} onChange={e=>setInviteNumber(e.target.value)} placeholder="Number to invite" className="w-full bg-gray-100 rounded-full px-4 py-2 text-sm outline-none mb-2"/><button onClick={inviteViaWhatsApp} className="w-full py-2 bg-green-500 text-white rounded-full text-sm font-semibold">Invite via WhatsApp</button></div></div></div></div>}
  </div>;
}
